/obj/machinery/mineral/ore_redemption/examine(mob/user)
	. = ..()
	if(in_range(user, src) || isobserver(user))
		. += span_notice("Smelting <b>[ore_multiplier]</b> sheet(s) per piece of ore.")
		. += span_notice("Reward point generation at <b>[point_upgrade * 100]%</b>.")

/obj/machinery/mineral/ore_redemption/RefreshParts()
	. = ..()
	point_upgrade = initial(point_upgrade)
	ore_multiplier = initial(ore_multiplier)
	for(var/datum/stock_part/matter_bin/bin in component_parts)
		ore_multiplier = round(0.65 + (0.35 * bin.tier), 0.01)
	for(var/datum/stock_part/micro_laser/laser in component_parts)
		point_upgrade = 0.65 + (0.35 * laser.tier)
