//Security levels
#define SEC_LEVEL_GREEN 0
#define SEC_LEVEL_BLUE 1
#define SEC_LEVEL_VIOLET 2
#define SEC_LEVEL_ORANGE 3
#define SEC_LEVEL_AMBER 4
#define SEC_LEVEL_RED 5
#define SEC_LEVEL_BLACK 6 // OCULIS EDIT ADDITION
// OCULIS EDIT START
#define SEC_LEVEL_DELTA 7
#define SEC_LEVEL_EPSILON 8 // CENTCOM IS ANGY!!!
#define SEC_LEVEL_GAMMA 9 // Oh shit bois
#define SEC_LEVEL_FEDERAL 10 // THE FUCKING FEDS ARE HERE!!!
// OCULIS EDIT END
